// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by rustok_mobile/tooling/scripts/generate_mobile_manifest.py

import 'package:app_module_contracts/app_module_contracts.dart';

const generatedMobileManifest = <MobileModuleEntry>[
  MobileModuleEntry(
    moduleKey: 'rustok_blog',
    routeSegment: 'blog',
    localeNamespace: 'blog',
    nav: MobileNavMeta(title: 'Blog', icon: 'article'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'new',
        title: 'Add Blog Post',
        navLabel: 'Add Post',
      ),
      MobileChildPage(
        subpath: 'posts',
        title: 'All Blog Posts',
        navLabel: 'All Posts',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_channel',
    routeSegment: 'channels',
    localeNamespace: 'channel',
    nav: MobileNavMeta(title: 'Channels', icon: 'module'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'apps',
        title: 'Channel Apps',
        navLabel: 'Apps',
      ),
      MobileChildPage(
        subpath: 'targets',
        title: 'Channel Targets',
        navLabel: 'Targets',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_comments',
    routeSegment: 'comments',
    localeNamespace: 'comments',
    nav: MobileNavMeta(title: 'Comments', icon: 'chat'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_commerce',
    routeSegment: 'commerce',
    localeNamespace: 'commerce',
    nav: MobileNavMeta(title: 'Commerce', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_customer',
    routeSegment: 'customers',
    localeNamespace: 'customer',
    nav: MobileNavMeta(title: 'Customers', icon: 'people'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_forum',
    routeSegment: 'forum',
    localeNamespace: 'forum',
    nav: MobileNavMeta(title: 'Forum', icon: 'forum'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'categories',
        title: 'Forum Categories',
        navLabel: 'Categories',
      ),
      MobileChildPage(
        subpath: 'topics',
        title: 'Forum Topics',
        navLabel: 'Topics',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_fulfillment',
    routeSegment: 'fulfillment',
    localeNamespace: 'fulfillment',
    nav: MobileNavMeta(title: 'Fulfillment', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_index',
    routeSegment: 'index',
    localeNamespace: 'index',
    nav: MobileNavMeta(title: 'Index', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_inventory',
    routeSegment: 'inventory',
    localeNamespace: 'inventory',
    nav: MobileNavMeta(title: 'Inventory', icon: 'inventory'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_media',
    routeSegment: 'media',
    localeNamespace: 'media',
    nav: MobileNavMeta(title: 'Media', icon: 'perm_media'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_order',
    routeSegment: 'orders',
    localeNamespace: 'order',
    nav: MobileNavMeta(title: 'Orders', icon: 'receipt_long'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_outbox',
    routeSegment: 'outbox',
    localeNamespace: 'outbox',
    nav: MobileNavMeta(title: 'Outbox', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pages',
    routeSegment: 'pages',
    localeNamespace: 'pages',
    nav: MobileNavMeta(title: 'Pages', icon: 'module'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'all',
        title: 'All Pages',
        navLabel: 'All Pages',
      ),
      MobileChildPage(
        subpath: 'new',
        title: 'Add Page',
        navLabel: 'Add Page',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pricing',
    routeSegment: 'pricing',
    localeNamespace: 'pricing',
    nav: MobileNavMeta(title: 'Pricing', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_product',
    routeSegment: 'product',
    localeNamespace: 'product',
    nav: MobileNavMeta(title: 'Products', icon: 'inventory_2'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_rbac',
    routeSegment: 'rbac',
    localeNamespace: 'rbac',
    nav: MobileNavMeta(title: 'RBAC', icon: 'shield'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_region',
    routeSegment: 'regions',
    localeNamespace: 'region',
    nav: MobileNavMeta(title: 'Regions', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_search',
    routeSegment: 'search',
    localeNamespace: 'search',
    nav: MobileNavMeta(title: 'Search', icon: 'search'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'analytics',
        title: 'Search Analytics',
        navLabel: 'Analytics',
      ),
      MobileChildPage(
        subpath: 'dictionaries',
        title: 'Search Dictionaries',
        navLabel: 'Dictionaries',
      ),
      MobileChildPage(
        subpath: 'engines',
        title: 'Search Engines',
        navLabel: 'Engines',
      ),
      MobileChildPage(
        subpath: 'playground',
        title: 'Search Playground',
        navLabel: 'Playground',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_seo',
    routeSegment: 'seo',
    localeNamespace: 'seo',
    nav: MobileNavMeta(title: 'SEO', icon: 'travel_explore'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'overview',
        title: 'SEO Overview',
        navLabel: 'Overview',
      ),
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_tenant',
    routeSegment: 'tenant',
    localeNamespace: 'tenant',
    nav: MobileNavMeta(title: 'Tenant', icon: 'apartment'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_workflow',
    routeSegment: 'workflow',
    localeNamespace: 'workflow',
    nav: MobileNavMeta(title: 'Workflow', icon: 'account_tree'),
    childPages: <MobileChildPage>[
      MobileChildPage(
        subpath: 'templates',
        title: 'Workflow Templates',
        navLabel: 'Templates',
      ),
    ],
  ),
];
