pub mod admin_events;
pub mod alloy;
pub mod auth;
pub mod blog;
pub mod commerce;
pub mod content;
pub mod forum;
pub mod graphql;
pub mod health;
#[cfg(feature = "mod-media")]
pub mod media;
pub mod metrics;
pub mod oauth;
pub mod oauth_metadata;
pub mod pages;
pub mod swagger;
pub mod users;
#[cfg(feature = "mod-workflow")]
pub mod workflow;
