// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by rustok_mobile/tooling/scripts/generate_mobile_manifest.py

import 'package:app_module_contracts/app_module_contracts.dart';

const generatedMobileManifest = <MobileModuleEntry>[
  MobileModuleEntry(
    moduleKey: 'rustok_blog',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'blog',
    localeNamespace: 'blog',
    nav: MobileNavMeta(title: 'Blog', icon: 'article'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_cart',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'cart',
    localeNamespace: 'cart',
    nav: MobileNavMeta(title: 'Cart', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_commerce',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'commerce',
    localeNamespace: 'commerce',
    nav: MobileNavMeta(title: 'Commerce', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_forum',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'forum',
    localeNamespace: 'forum',
    nav: MobileNavMeta(title: 'Forum', icon: 'forum'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pages',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'pages',
    localeNamespace: 'pages',
    nav: MobileNavMeta(title: 'Pages', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pricing',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'pricing',
    localeNamespace: 'pricing',
    nav: MobileNavMeta(title: 'Pricing', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_product',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'products',
    localeNamespace: 'product',
    nav: MobileNavMeta(title: 'Products', icon: 'inventory_2'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_region',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'regions',
    localeNamespace: 'region',
    nav: MobileNavMeta(title: 'Regions', icon: 'module'),
    childPages: <MobileChildPage>[
    ],
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_search',
    surfaceKind: MobileSurfaceKind.storefront,
    routeSegment: 'search',
    localeNamespace: 'search',
    nav: MobileNavMeta(title: 'Search', icon: 'search'),
    childPages: <MobileChildPage>[
    ],
  ),
];
